const beasts =
    [
        { name: "Alghul", weakness: 46, cluster: "Trupojady" },
        { name: "Alp", weakness: 45, cluster: "Wampiry" },
        { name: "Arachnomorf", weakness: 350, cluster: "Insektoidy" },
        { name: "Archespor", weakness: 460, cluster: "Istory przeklęte" },
        { name: "Baba Cmentarna", weakness: 45, cluster: "Trupojady" },
        { name: "Baba Wodna", weakness: 450, cluster: "Trupojady" },
        { name: "Barghest", weakness: 45, cluster: "Upiory" },
        { name: "Bazyliszek", weakness: 462, cluster: "Drakonoidy" },
        { name: "Bies", weakness: 360, cluster: "Relikty" },
        { name: "Bies Tygrysi", weakness: 360, cluster: "Relikty" },
        { name: "Bloedzuiger", weakness: 360, cluster: "Trupojady" },
        { name: "Borowy", weakness: 360, cluster: "Relikty" },
        { name: "Cyklop", weakness: 36, cluster: "Ogrowate" },
        { name: "Czart", weakness: 36, cluster: "Relikty" },
        { name: "Ekimma", weakness: 360, cluster: "Wampiry" },
        { name: "Endriaga Robotnica", weakness: 350, cluster: "Insektoidy" },
        { name: "Endriaga Truteń", weakness: 360, cluster: "Insektoidy" },
        { name: "Fleder", weakness: 36, cluster: "Wampiry" },
        { name: "Gargulec", weakness: 361, cluster: "Istoty Magiczne" },
        { name: "Garkain", weakness: 46, cluster: "Wampiry" },
        { name: "Ghul", weakness: 452, weakness_sword: "Srebro", weakness_attack: "Szybki", weakness_element: "none", cluster: "Trupojady" },
        { name: "Ghul Bladolicy", weakness: 45, cluster: "Trupojady" },
        { name: "Golem", weakness: 1, cluster: "Istoty Magiczne" },
        { name: "Gryf", weakness: 3502, cluster: "Hybrydy" },
        { name: "Harpia", weakness: 3502, cluster: "Hybrydy" },
        { name: "Jadowity Krabopająk", weakness: 350, cluster: "Insektoidy" },
        { name: "Kikimora Robotnica", weakness: 350, cluster: "Insektoidy" },
        { name: "Krabopająk Królewski", weakness: 36, cluster: "Insektoidy" },
        { name: "Krabopająk Pospolity", weakness: 350, cluster: "Insektoidy" },
        { name: "Krabopająk Pustelnik", weakness: 36, cluster: "Insektoidy" },
        { name: "Mglak", weakness: 452, cluster: "Trupojady" },
        { name: "Milczący", weakness: 45, cluster: "Upiory" },
        { name: "Nekker", weakness: 452, cluster: "Ogrowate" },
        { name: "Nekker Bagienny", weakness: 452, cluster: "Ogrowate" },
        { name: "Nekker Wojownik", weakness: 46, cluster: "Ogrowate" },
        { name: "Nekker Rzeźnik", weakness: 46, cluster: "Ogrowate" },
        { name: "Ogar Borowego", weakness: 360, cluster: "Relikty" },
        { name: "Pijawiec", weakness: 360, cluster: "Trupojady" },
        { name: "Południca", weakness: 45, cluster: "Upiory" },
        { name: "Północnica", weakness: 45, cluster: "Upiory" },
        { name: "Raraszek", weakness: 36, cluster: "Drakonidy" },
        { name: "Silvan", weakness: 36, cluster: "Relikty" },
        { name: "Skolopendromorf", weakness: 36, cluster: "Insektoidy" },
        { name: "Skrzat", weakness: 45, cluster: "Istoty Magiczne" },
        { name: "Sukkub", weakness: 352, cluster: "Hybrydy" },
        { name: "Syrena", weakness: 4502, cluster: "Hybrydy" },
        { name: "Szarlej", weakness: 362, cluster: "Relikty" },
        { name: "Troll Skalny", weakness: 362, cluster: "Ogrowate" },
        { name: "Upiór", weakness: 45, cluster: "Upiory" },
        { name: "Utopiec", weakness: 460, cluster: "Trupojady" },
        { name: "Wicht", weakness: 45, cluster: "Trupojady" },
        { name: "Wij", weakness: 35, cluster: "Insektoidy" },
        { name: "Widłogon", weakness: 362, cluster: "Drakonidy" },
        { name: "Widłogon Zielony", weakness: 36, cluster: "Drakonidy" },
        { name: "Wilkołak", weakness: 450, cluster: "Istoty Przeklęte" },
        { name: "Wodnik", weakness: 350, cluster: "Ogrowate" },
        { name: "Wywerna", weakness: 36, cluster: "Drakonidy" },
        { name: "Zgnilec", weakness: 450, cluster: "Trupojady" },
        { name: "Ropucha Olbrzymia", weakness: 35, cluster: "Istoty Przelęte" },
        { name: "Szarlej", weakness: 352, cluster: "" },



        { name: "Nekker Królewski", weakness: 452, cluster: "Ogrowate" },
        { name: "Truchlica", weakness: 45, cluster: "Trupojady" },
        { name: "Ogar Leszego", weakness: 360, cluster: "Relikty" },
        { name: "Widłogon Siny", weakness: 362, cluster: "Drakonidy" },
        { name: "Zjadarka", weakness: 462, cluster: "Trupojady" },
        { name: "Mglak Królewski", weakness: 452, cluster: "Trupojady" },
        { name: "Troll Magmowy", weakness: 362, cluster: "Ogrowate" },
        { name: "Leszy", weakness: 360, cluster: "Relikty" },
        { name: "Skrzekacz", weakness: 4602, cluster: "Drakonidy" },
        { name: "Licho", weakness: 362, cluster: "Upiory" },
        { name: "Grotnik", weakness: 36, cluster: "Relikty" },
        { name: "IgnisFatuus", weakness: 452, cluster: "Trupojady" },
        { name: "Kamienny Golem", weakness: 1, cluster: "Magiczne Istoty" },
        { name: "Endriaga Wojownik", weakness: 360, cluster: "Insektoidy" },
        { name: "Bruxa", weakness: 450, cluster: "Wampiry" },
        { name: "Beann'shie", weakness: 45, cluster: "Upiory" },

        { name: "Lodowy Gigant", weakness: 360, cluster: "Ogrowate" },
        { name: "Przeraza", weakness: 46, cluster: "Insektoidy" },
    ];
    export default beasts;